// INDIVIDUAL MARKERS //
// goverment_miltiary
var g1 = L.marker([82, -143], {icon: gov_mil1}).bindPopup("<h3 style='text-align:center'>Jeggare Light</h3> The lighthouse the first Korvosan building that was built outside the fort's initial walls. Veranada Mezzerae is an aged Sable-Marine and the lighthouse's sole keeper and communicator.");
var g2 = L.marker([64, 55.6], {icon: gov_mil2}).bindPopup("<h3 style='text-align:center'>Longacre Building</h3> Also known as Arbiter's Hall, is an imposing building that serves as both a jail and a courthouse. It has in times past acted as a garrison of sorts as well, and its upper levels are still equipped to house a small army.");
var g3 = L.marker([64, 66], {icon: gov_mil3}).bindPopup("<h3 style='text-align:center'>North Point City Hall</h3> One of Queen Ileosa's first edict was to move much of the workings of the goverment out of this building and back into Castle Korvosa, as is ordained by Cheliaxan tradition. The building still maintains a skeleton crew of clerks that cannot handle the increased workload.")
var g4 = L.marker([51, 87], {icon: gov_mil4}).bindPopup("<h3 style='text-align:center'>Korvosa’s Mercy</h3> The largest and first of Korvosa’s state-run orphanages, Korvosa’s Mercy has a long-standing association with the military. ")
var g5 = L.marker([55.5, -92.4], {icon: gov_mil5}).bindPopup("<h3 style='text-align:center'>Great Tower</h3> This incomplete tower serves the Sable Company as an armory, a barracks, and a stable for their hippogriffs. As the Sable Company loses ranks and influence, rumors of its inevitable dismantling spread like wildfire.")
var g6 = L.marker([-30, -69.8], {icon: gov_mil6}).bindPopup("<h3 style='text-align:center'>Castle Korvosa</h3>Easily the most imposing structure in the city, Castle Korvosa is the fortress-citadel home of the monarchs Korvosa. The castle itself is built on an ancient four-sided, flat-topped pyramid known as the Grand Mastaba, built millennia ago by the Shoanti people. It can be seen from anywhere in the city.")
var g7 = L.marker([24.6, 59.5], {icon: gov_mil7}).bindPopup("<h3 style='text-align:center'>Scrapper Hall</h3>Although this building is relatively small, the highly regimented work hours that orphans endure here push the limits of legality, and the orphanage’s staff members often clash with the priestly inspectors from both Abadar and Sarenrae’s faith.")
var g8 = L.marker([14, 62.4], {icon: gov_mil8}).bindPopup("<h3 style='text-align:center'>Riverside House</h3> This mid-sized orphanage is also Korvosa’s oldest. Tragically, the builting has burned to the ground during the week-long turmoil and revolt that followed King Eodred's death. Rumors say its staff and children still haunt the burned ruins on the 4th of each month.")
var g9 = L.marker([-38.9, 15.2], {icon: gov_mil9}).bindPopup("<h3 style='text-align:center'>Warehouses</h3> A large complex of warehouses, primarily belonging to the noble dock families that dictate much of Korvosa's commerce. Independent warehouses are rarer, much smaller and can typically afford less protection than their noble counterparts.")
var g10 = L.marker([-55, 47], {icon: gov_mil10}).bindPopup("<h3 style='text-align:center'>Citadel Volshyenek</h3> The main garrison for the Korvosan Guard. The citadel serves as the centre of command for all military operations, and even has its own cells at the bottom to hold prisoner’s until they are transferred to be judged. The current Field Marshal of the guard is Cressida Kroft.")
var g11 = L.marker([-68.4, -50], {icon: gov_mil11}).bindPopup("<h3 style='text-align:center'>Dawnflower House</h3>While all five of Korvosa’s orphanages are inspected regularly by the churches of Abadar (to ensure everything is running efficiently and legally) and by Sarenrae (to ensure the children are safe and comfortable), Dawnflower House is the only one of the five to be run by actual clerics.")
var g12 = L.marker([-30, 157.4], {icon: gov_mil12}).bindPopup("<h3 style='text-align:center'>Little House</h3>The smallest of Korvosa’s orphanages is also the newest. Administered by a philanthropic halfling named Bek Blerkian, the Little House focuses primarily on non-human orphans.")
var g13 = L.marker([-81.214853, -162.333984], {icon: gov_mil13}).bindPopup("<h3 style='text-align:center'>Jeggare Isle</h3> A single squat fort sits atop this low, rocky isle, its roof adorned with several siege engines. These days, Jeggare Isle is in large part a nostalgic historical site from the city’s violent past, and while its defenses still function, its skeleton crew can hardly man them with efficiency should the need arise.")
// homes_inns
var h1 = L.marker([77, -102], {icon: homes_inns1}).bindPopup("<h3 style='text-align:center'>Arkona Palace</h3>This manor houses Old Korvosa’s de facto ruling family, the inscrutable, but respected, House Arkona. In the past a family on the verge of financial ruin, a favourable business partnership with Vudra has made the Arkonas the second richest family in Korvosa. A strong opponent to the royalty, Glorio Arkona leads the other houses in their attempts to keep the monarchy balanced and fair in their judgement.The grounds are generally open, decorated here and there with tiny copses of trees, exotic topiary animals, expansive flower gardens and fountains. The palace is a breathtaking structure built in the Vudran style.");
var h2 = L.marker([76.820793, -64.335938], {icon: homes_inns2}).bindPopup("<h3 style='text-align:center'>Vencarlo Orisini's Manor</h3>This solid, comfortable and unassuming house may look old from the outside, but within, it is in excellent repair.")
var h3 = L.marker([75.275413, 3.779297], {icon: homes_inns3}).bindPopup("<h3 style='text-align:center'>Ruin's Way</h3> These run-down houses are typical of so many old and decaying homes in Old Korvosa. They typically belong to criminals, dockworkers or destitute eccentric artists.");
var h4 = L.marker([80.208652, 34.980469], {icon: homes_inns4}).bindPopup("<h3 style='text-align:center'>Ramshackkle Tenements</h3> These houses form what is perhaps one of the most abhorrent neighborhood of Korvosa, second in poverty and filth only to Bridgefront.");
var h5 = L.marker([82.3558, 115.3125], {icon: homes_inns5}).bindPopup("<h3 style='text-align:center'>Trail's End</h3> These humble homes are part of Korvosa's heavily Varisian outlying neighborhood. Watch Seargent Grau Soldado makes his home here as well, living with his dead brother's family.");
var h6 = L.marker([61.354614, -61.611328], {icon: homes_inns6}).bindPopup("<h3 style='text-align:center'> Posh & Turtle</h3>The finest inn and tavern in all of Korvosa. Upon entering the establishment, it is difficult not to notice the glass flooring overlooking a wide but shallow sea cave, within which lives a 20-foot-long sea turtle named Old Tom. The owner of the establishment, Thaviun Rigulus, is a wizard of some repute.");
var h7 = L.marker([78.170582, 13.886719], {icon: homes_inns7}).bindPopup("<h3 style='text-align:center'>Laughing Wave</h3> Saul Vancaskerkin's pride and joy, it was previously the oldest surviving inn from Korvosa's early days. A sudden change in ownership threatened to see the inn distmantled - but Saul stepped in and bought it for himself. Now, it is part gambling den, part fighting pit - run as a front by Saul's gang. Its prior prestige only adds to its current success.");
var h8 = L.marker([65.766727, 78.398438], {icon: homes_inns8}).bindPopup("<h3 style='text-align:center'>Whitecaps Inn</h3> Whitecaps is an inn more than a century past its prime. It looks old, itsmells old, and it even feels old to those inside it.");
var h9 = L.marker([28.536275, -109.863281], {icon: homes_inns9}).bindPopup("<h3 style='text-align:center'>Upslope House</h3> This fine inn can accomodate up to 22 people in its 10 rooms. Its position, close to both the Temple of Asmodeus as well as the Acadamae, makes it a favoured establishment for visiting clergy and professors.");
var h10 = L.marker([17.644022, -108.325195], {icon: homes_inns10}).bindPopup("<h3 style='text-align:center'>Frisky Unicorn</h3> This  inn's main claim to fame is its rooms: The rooms in this comparatively low-priced inn, given its location in The Heights, can afford breathtaking views of Conqueror's Bay.");
var h11 = L.marker([6.402648, -19.072266], {icon: homes_inns11}).bindPopup("<h3 style='text-align:center'>Wise Dragon Inn</h3>Normally, this inn caters to students who haven’t yet secured housing at the Acadamae, but when the Acadame closed its doors indefinitely, many of its students went back home. This has made management desperate for patronage.");
var h12 = L.marker([-20.13847, -37.617188], {icon: homes_inns12}).bindPopup("<h3 style='text-align:center'>Tenna's </h3> Boasting the title of Korvosa's most expensive inn, Tenna's makes up for its prices by offering unparalled amenities: scented baths, massages, valets, three lavish meals per day - to name just some of the highlights. The staff all speak very highly of Mistress Tenna, but nobody can tell you what she looks like.");
var h13 = L.marker([-11.307708, -9.799805], {icon: homes_inns13}).bindPopup("<h3 style='text-align:center'>Trinia's Flat</h3> Located on the top floor of a sprawling tenement complex known as The Shackles, this small flat is home to Trinia Sabor.")
var h14 = L.marker([-22.350076, -8.085938], {icon: homes_inns14}).bindPopup("<h3 style='text-align:center'>Feeding Hole</h3> Next to one of the many otyugh-feeding holes in the city that has still not been repaired after recent events have seen otyughs rampage on the city's surface, this foul tavern attracts unusual clientel that hope to see the sewer monsters during their stay. It is also built on top of a main-sewer line, which only adds to the smell.");
var h15 = L.marker([-45.213004, 22.851563], {icon: homes_inns15}).bindPopup("<h3 style='text-align:center'>Zellara’s Home</h3> This humble abode is where Zellara first read your fortunes and saw you spearhead Korvosa's salvation in her time of need. It now stands abandoned and decrepit, save for a tapestry depicting a warrior holding a flaming sword in his skeletal hand. Behind him are shadowy figures that seem to follow his footsteps. Perhaps still a place of power, Zellara's spirit asks you to bring the deck here whenever she does a reading.");
var h16 = L.marker([-60.973107, 38.496094], {icon: homes_inns16}).bindPopup("<h3 style='text-align:center'>Creaky Hammock</h3> Decorated with nautical themes, this tavern tends to serve ships' crews in port and sees little patronage otherwise save for the odd Korvosan Guard.")
var h17 = L.marker([-20.715015, 135.175781], {icon: homes_inns17}).bindPopup("<h3 style='text-align:center'>Bard's End</h3> Standing just a block from Kendall Amphiteater, Korvosa's largest inn provides a place to stay for those who have travelled long and far.");
var h18 = L.marker([-78.971386, -85.78125], {icon: homes_inns18}).bindPopup("<h3 style='text-align:center'>Leftover's</h3> East Shore's only inn. It contains a dozen two-person rooms in addition to a large, cozy common room. It does not have much traffic, since most of Korvosa's visitors have little business in South Shore. The only regular clientele comes from guests of the Pharasmian clergy.");
var h19 = L.marker([-82.166446, -119.047852], {icon: homes_inns19}).bindPopup("<h3 style='text-align:center'>The Summit</h3>An alliance of merchant elites and new nobles who have attained nobility during the reign of King Eodred I. Although some would say they are gaudish, their homes look more like Magnimar's marbled homes rather than the Cheliax-inspired Korvosan architecture.");
// restaurants_taverns
var r1 = L.marker([81.582843, 21.972656], {icon: rest_tavern1}).bindPopup("<h3 style='text-align:center'>Sticky Mermaid</h3> A fixture of Old Dock for more than two centuries, this is an unholesome tavern that serves unruly clientele made all the rougher by fishjack, a particularly potent spirit served only here and garnished with fermented eggs of Jeggare River salmon.");
var r2 = L.marker([81.723188, 46.494141], {icon: rest_tavern2}).bindPopup("<h3 style='text-align:center'>Jeggare's Jug</h3> One of the many small pubs that fill Old Dock, Jeggy's Jug maintains a heated rivalry with the Sticky Mermaid. The clinetele at the Jug is made up out of cranky dockworkers and surl laborers.");
var r3 = L.marker([78.420193, 1.142578], {icon: rest_tavern3}).bindPopup("<h3 style='text-align:center'>Travelling Man</h3>In addition to its extensive variety of beverages—alcoholic and not— this small tavern and coffehouse gathers a regular breakfast clientele with its Varisian sweetbreads and cream-filled pastries. Before quitting to join the Korvosan Guard, Anya worked here as a late-night dancer.");
var r4 = L.marker([45.890008, 74.970703], {icon: rest_tavern4}).bindPopup("<h3 style='text-align:center'>Three Rings Tavern</h3> This tavern is low-key and quiet, serving as much coffee and tea as mead and wine. It is run by a Desna worshippers named Callum whose main claim to fame is his coffe brewing, which he claims he's learned while on a mission to Garund.");
var r5 = L.marker([40.313043, -2.460938], {icon: rest_tavern5}).bindPopup("<h3 style='text-align:center'>Jittery Quill</h3>This low-key establishment serves both ale and coffee, making it the favorite haunt of university students and faculty alike.");
var r6 = L.marker([-64.396938, -132.626953], {icon: rest_tavern6}).bindPopup("<h3 style='text-align:center'>Overlook</h3> Teetering on a cliff edge, the Overlook gets a little closer to falling into the raging surf below every year due to erosion. This hint of danger carries over to the tavern's signature offering, made from whatever castoff ingredients happen to be on hand at the time.");
var r7 = L.marker([-66.75725, -103.886719], {icon: rest_tavern7}).bindPopup("<h3 style='text-align:center'>Crested Falcon</h3> One of the most expensive restaurants in Korvosa, and easily the most overpriced, the Crested Falcon's extravagant menu changes each day.");
var r8 = L.marker([-38.822591, 23.554688], {icon: rest_tavern8}).bindPopup("<h3 style='text-align:center'>Bailer's Retreat</h3> This rough tavern is a favorite destination of recently released prisoners from Citadel Volshyenek's jails. As a result, brawls and resultant visits from the Korvosan Guard, are frequent occurences here.");
var r9 = L.marker([-59.489726, 104.0625], {icon: rest_tavern9}).bindPopup("<h3 style='text-align:center'>Shoreline Drinkhall</h3> The most popular of the few taverns in East Shore, The Drinkhall has a reputation for fair prices and stiff drinks, although it smeal offerings taste more like military rations than tavern food. This is no accident - as many of its staff are retired Korvosan guards.");
var r10 = L.marker([-79.004962, -73.476563], {icon: rest_tavern10}).bindPopup("<h3 style='text-align:center'>Jade Circle</h3> Taking much of its decor from Tian Xia, the walls of this green-painted, domed teahouse glitter like giant emeralds in the sun. By day, young nobles accompany their parents for exotic fragrant teas. By night, young bravos bolster their spirits with mulled wine and heroic tales.");
// shops_services
var s1 = L.marker([80.900669, -12.832031], {icon: shop_service1}).bindPopup("<h3 style='text-align:center'>Reefclaw Rum Market</h3>Fresh seafood remains the order of the day at this market and little else, as it has been for almost 3 centuries.");
var s2 = L.marker([79.935918, 53.789063], {icon: shop_service2}).bindPopup("<h3 style='text-align:center'>Copper-Beater Hall</h3>This forge has been abandoned during the riots following King Eodred's death. Squatters have taken it over, using its coals to keep themselves warm during the cold nights.");
var s3 = L.marker([77.841848, 54.316406], {icon: shop_service3}).bindPopup("<h3 style='text-align:center'>Eel's End</h3> A tangle of five ships moored to at the eastern end of the Narrows, this clot of decomissioned ships is ruled by a man named Devargo Barvasi, known to many as the King of Spiders.");
var s4 = L.marker([76.679785, -13.886719], {icon: shop_service4}).bindPopup("<h3 style='text-align:center'>Hessim's Paint Manufactory</h3>This building caters to Korvosa's struggling artist community, offering hundreds of tiny jars and pots, brushed, canvases and easels. Trinia's friend Hessim runs the place.");
var s5 = L.marker([73.553302, -108.193359], {icon: shop_service5}).bindPopup("<h3 style='text-align:center'>Giottori's Toys</h3> Located near Racker's Alley, an area known to be a haven for illicit exchanges, this shop proudly displays horrifying toys that keeps children away. Rather, it attracts a more dubious clientele.");
var s6 = L.marker([72.738003, -81.386719], {icon: shop_service6}).bindPopup("<h3 style='text-align:center'>Ironworks</h3>Korvosa's factory focuses on simple and functional wrought-iron goods, emphasising quantity over quality. Its most charitable donor is Glorio Arkona. During the city's trouble with The Children of the Sun, large numbers of the factory's workers were accused of being members - but these accusations could not be proven.");
var s7 = L.marker([67.067433, 36.210938], {icon: shop_service7}).bindPopup("<h3 style='text-align:center'>Dock Trade</h3> This market of questionable legality offers good that appear brand new, although most have some amount of minor damage to them. Many of the merchants here have ties to the Cerulean Society or other criminal organizations.");
var s8 = L.marker([39.774769, 94.042969], {icon: shop_service8}).bindPopup("<h3 style='text-align:center'>All the World's Meat</h3> This butcher shop had been closed for nearly a year but was briefly reopened by a deranged group called the Cow Hammer Boys, before being stopped by the Korvosan Guard. They were selling cheap 'meat' in times of trouble that was discovered to be discarded human remains from their side-work as hired assassins.");
var s9 = L.marker([14.093957, -88.417969], {icon: shop_service9}).bindPopup("<h3 style='text-align:center'>Lavender</h3>A relatively new establishment devoted to the sales of perfumes and other distractions aimed at the rich and elite.");
var s10 = L.marker([6.315299, -81.386719], {icon: shop_service10}).bindPopup("<h3 style='text-align:center'>Gilded Orrery</h3> Specializing in magic items and texts in support of conjuration magic, the Gilded Orrery also stocks a wide selection of other magical wares and books of arcane lore. Its owner, Hassman Gruber, is a powerful retired wizard that was at one point the Acadamae's treasurer. He runs his shop entirely remotely via a crystal ball, while the numerous traps inside his shop make sure to repell would-be thieves.");
var s11 = L.marker([8.581021, 24.433594], {icon: shop_service11}).bindPopup("<h3 style='text-align:center'>Bookmaker</h3> Korvosa's largest bookstore, this site also publishes its own small-press tomes on a wide range of subjects written mostly by local scholars. Although not overtly-partisan to any college, House Leroung (whose lady is the current headmistress of the University of Korvosa) is their biggest sponsor.");
var s12 = L.marker([-17.811456, 36.5625], {icon: shop_service12}).bindPopup("<h3 style='text-align:center'>Old Fishery</h3> Known primarily for producing low-cost, no-questions-asked fish slurry, this was the secret lair of the aging criminal Gaedrin Lamm - whose death had been foretold by Zellara as both necessary to bring the heroes together, as well as catalist for great tragedy.");
var s13 = L.marker([-58.539595, -2.636719], {icon: shop_service13}).bindPopup("<h3 style='text-align:center'>Gold Market</h3>Korvosa's largest marketplace serves as the main attraction in Midland. All manner of foods and handicraft from Korvosa's holdings and the rest of Varisia appear on display.");
var s14 = L.marker([-54.470038, 7.558594], {icon: shop_service14}).bindPopup("<h3 style='text-align:center'>Eodred's Walk</h3>Fourteen shops form the semicircular face of Eodred's walk, offering a variety of goods and services including but not limited to books and maps, harrow readings, jewelry, minor magical trinkets, haircuts and grooming, smoked food, clocks and clockwork trinket and hunting supplies.");
var s15 = L.marker([-71.187754, -31.816406], {icon: shop_service15}).bindPopup("<h3 style='text-align:center'>Pestico's Dolls</h3>A doddering but gentle old man little more than a loud noise away from the grave, Vadid Pestico has lived and worked his entire life in Korvosa, crafting exquisite dolls for the city's children.");
var s16 = L.marker([-43.707594, 142.207031], {icon: shop_service16}).bindPopup("<h3 style='text-align:center'>Horse Shop</h3> A no-frills shop with fair prices, as its name implies, this shop doubles both as a livery stable as well as equestrian supply.");
var s17 = L.marker([-78.490552, -125.507813], {icon: shop_service17}).bindPopup("<h3 style='text-align:center'>Feathers & Furs</h3>Animal collectors and the wealthy nobles of The Summit acquire exotic pets or oddities to add to their menageries from here.");
var s18 = L.marker([-83.420215, -108.105469], {icon: shop_service18}).bindPopup("<h3 style='text-align:center'>Green Market</h3> This small, fully enclosed market specializes in food, clothing and commodities but it also provides jewelry and other luxuries for its nobles. Merchants here, however, are expressly forbidden by Summit Law from selling weapons, armor or magical items.");
// sites
var v1 = L.marker([78.134493, -76.992188], {icon: site1}).bindPopup("<h3 style='text-align:center'>Old City Hall</h3>This dark-brick building, sometimes affectionately called the Charcoal Palace, served as the city hall for 60 years. It is largely abandoned now, save for a tiny staff of caretakers. Chelaxian nobles often visit this place when in Korvosa, ammusing themselves at the colony's first attempt at 'civilization'.");
var v2 = L.marker([78.988187, 44.121094], {icon: site2}).bindPopup("<h3 style='text-align:center'>Exemplary Execrables</h3>Refurbished with gaudy, gold-colored paint and massive glass 'gems', this looming building is the home of a perverse and detestable theater of all things foul, gore slicked, and unnaturally pornographic. Volunteers at performances here often went missing after a show, only adding to this establishment's troubled reputation.");
var v3 = L.marker([77.273855, 25.751953], {icon: site3}).bindPopup("<h3 style='text-align:center'>Temple of Aroden</h3> Old and crumbling, Korvosa's Temple of Aroden has lost almost all its former splendor. Its outer-face is in complete disprepair, although the inner courtyard still stands and houses the 3 caretakers that run the place.");
var v4 = L.marker([75.845169, 110.390625], {icon: site4}).bindPopup("<h3 style='text-align:center'>Wreck of The Direption</h3> Whilst the heroes were away from Korvosa, a ship had infiltrated Korvosa's waters and ignored the guard's signal to anchor. As such, the guards sank the ship with cannonballs and the heroes were asked to investigate its remains: there, they found nothing of significance save for a pristinely-preserved copy of 'Serving your Hunger', the sacred text of Urgathoa worshippers.");
var v5 = L.marker([64.244595, -57.216797], {icon: site5}).bindPopup("<h3 style='text-align:center'>Avenue of Arms</h3>This bizarre landmark extends all along the wide thoroughfare, exactly 127 human-looking stone arms reaching up from the rocky soil along the road at an even distance. No two arms look the same, but despite variations, all of them have a few things in common: they face the same direction, with their elbows bending away from shore to point toward the road; they all look like the arms of human adults; all are evenly spaced at precise increments and they share the strange Thassilonian feature of resisting erosion and vandalism. Any attempt to dig up or damage the arms causes strange shrieks of pain and terror, as well as the welling up of brackish black water where the wound in the stone occurs. Today, the people of Korvosa have come to accept the Avenue of Arms as just another ancient curiosity—one that is better left alone.");
var v6 = L.marker([36.879621, 16.875], {icon: site6}).bindPopup("<h3 style='text-align:center'>Jeggare Museum</h3>Built and operated by House Jeggare, this large museum displays hundreds of objects pulled from ruins and archaeological sites scattered across Varisia. Mercival Jeggare, the museum’s curator, happily buys treasures and items from “freelance treasure hunters” for reasonable prices");
var v7 = L.marker([-52.589701, -69.785156], {icon: site7}).bindPopup("<h3 style='text-align:center'>Marbledome</h3>This gleaming fixture is home to Korvosa’s opera company, a poorly managed affair known for producing mediocre performances that bleed gold.");
var v8 = L.marker([-68.4638, -147.304688], {icon: site8}).bindPopup("<h3 style='text-align:center'>Gatefoot</h3> Clearly a Thassilonian relic, this is a well-proportioned but immense stone foot. As with all Thassilonian structures, old rumors hold that the foot marks the uppermost reaches of an extensive underground complex, yet no evidence of such has ever been found. To all appearances, the massive foot is nothing more than a remnant from a prior age.");
var v9 = L.marker([-72.60712, -98.789063], {icon: site9}).bindPopup("<h3 style='text-align:center'>Kendall Amphiteater</h3> Built by a joint efort between the Church of Abadar and a team of dwarven architects after a massive sinkhole appeared into the city, this site honors the heroism of Mina Kendall, the then-Field Marshal who died in the battle to stop the endless horde of monsters that streamed out of the sinkhole.");
var v10 = L.marker([-69.224997, 35.15625], {icon: site10}).bindPopup("<h3 style='text-align:center'>Eodred Square</h3>Forming a plaza just past the west end of High Bridge, the square makes a popular venue that locals and visitors alike use to set up meetings or to simply orient themselves within the ward.");
var v11 = L.marker([-77.196176, -85.429688], {icon: site11}).bindPopup("<h3 style='text-align:center'>Pillar Wall</h3>One of Korvosa’s many Thassilonian ruins, this row of 100-foot-tall stone pillars was once a small part of a much larger and more grandiose city defense, but it now serves as little more than a landmark.");
var v12 = L.marker([-80.444931, -20.390625], {icon: site12}).bindPopup("<h3 style='text-align:center'>Great Tomb of Leadership</h3> One of the largest crypts in Gray is the Great Tomb of Leadership, a heavily secured and constantly guarded building that holds the bodies of past military leaders and the city’s most-decorated soldiers");
var v13 = L.marker([-81.228267, 1.40625], {icon: site13}).bindPopup("<h3 style='text-align:center'>Dead Warrens</h3>One of many compact underground crypts below Korvosa’s Gray neighborhood, it is here where Zenna perished. Body-snatchers had stolen the body of a Shoanti who died during the rebellion following King Eodred's death, and with the tense relations between the native Shoanti and Korvosa, Field Marshal Cressida Kroft ordered the heroes to retrieve the body in order to prevent further altercations. What the heroes found below was an expansive and ghastly operation of derro-alchemists who engaged in sickening flesh-warping experiments at the command of a still-unknown necromancer.");
// temples_schools
var t1 = L.marker([79.088462, -63.369141], {icon: tems1}).bindPopup("<h3 style='text-align:center'>Orisini Academy/h3>This famed sword school stands in the heart of the city’s ancient center district. Within its walls, men and women—mostly young scions of noble houses—practice the many elegant skills of fencing and the grandiose arts of mobile swordplay");
var t2 = L.marker([78.733501, -47.548828], {icon: tems2}).bindPopup("<h3 style='text-align:center'>Endrin Military Academy</h3>These whitewashed buildings act as overflow barracks for Fort Korvosa’s small garrison of Korvosan Guards and Sable Company trainees. They also contain classrooms and sparring rings, although the amount of students are slowly dwindling and most of the remaining Korvosan Guard can fit comfortably in Citadel Volshyenek.");
var t3 = L.marker([56.848972, 74.179688], {icon: tems3}).bindPopup("<h3 style='text-align:center'>Bank of Abadar</h3>More than just a temple to the god of cities, the Bank of Abadar also serves as Korvosa’s main financial institution. During the plague, a schism grows in the church as some of its followers push to provide free healing for the poor (or at least at a reduced cost) to help protect the city—a stance many of the bank’s elder members, particularly its leader, Archbanker Darb Tuttle, see as a significant threat to the faith’s resources and traditions");
var t4 = L.marker([51.944265, 55.898438], {icon: tems4}).bindPopup("<h3 style='text-align:center'>Sanctuary of Shelin</h3> The Sanctuary of Shelyn is the smallest of the independent temples in the city - the goddess of art and beauty has little to oversee in Korvosa during these troubled times.");
var t5 = L.marker([35.603719, -72.597656], {icon: tems5}).bindPopup("<h3 style='text-align:center'>The Acadamae</h3>One of the most prestigious arcane institutions in the Inner Sea, the Acadamae is for the rich and talented only. Students are expected to specialize in a school of magic, but the primary focus under the ever-scowling headmaster Toff Ornelos is conjuration. Following King Eodred's death, the Acadamae senses a time of trouble and closes its doors tightly to visitors. They and their powerful faculty members have either holed up inside or have gone to their respective homes outside Korvosa.");
var t6 = L.marker([15.623037, -9.84375], {icon: tems6}).bindPopup("<h3 style='text-align:center'>University of Korvosa</h3> While it pales next to the grandeur of the Acadamae, the University of Korvosa proudly offers classes in all manner of subjects, and its faculty members are eager to point out that they don’t limit their scholastic pursuits to only magic — a thinly veiled jibe at their greatest competitors.");
var t7 = L.marker([4.390229, -123.398438], {icon: tems7}).bindPopup("<h3 style='text-align:center'>Temple of Asmodeus</h3> This starshaped temple hosts a relatively small number of priests of Asmodeus, who do little to involve themselves in the workings of the city. For most, this awe-inspiring building is little more than a feat of architecture and a relic of Korvosa's collonial roots - but undoubtedly the many worshippers of the Dark Prince still flock to this place of power.");
var t8 = L.marker([-63.154355, -113.730469], {icon: tems8}).bindPopup("<h3 style='text-align:center'>Temple of Sarenrae</h3> A many-turreted, white-marble temple filled with tireless priesthood in worship of The Dawnflower, Sarenrae's worshippers are a pillar of Korvosa's religious community.");
var t9 = L.marker([-5.266008, 168.046875], {icon: tems9}).bindPopup("<h3 style='text-align:center'>Theumanexus College</h3>This small school focuses on arcane magic, with a specific concentration on generalist magic that often puts its professors and students at odds with their competitors at the Acadamae.");
var t10 = L.marker([-81.255032, -67.851563], {icon: tems10}).bindPopup("<h3 style='text-align:center'>Pantheon of Many</h3> The Pantheon of Many holds shrines to 17 different deities within its white-marbled walls. Only Gorum, Lamashtu, and Rovagug do not have shrines present, for these three deities have traditionally been unpopular in Korvosa. Of late, the shrine to Norgorber has gone untended as well.");
var t11 = L.marker([-79.997168, -33.75], {icon: tems11}).bindPopup("<h3 style='text-align:center'>Grand Cathedral of Pharasma</h3>As in many cities, Pharasmins are the keepers of the dead and the monitors of fate in Korvosa. Staunchly opposed against ressurection magic - which they deem unnatural and an insult towards The Lady of Graves, their philosophy is stern but fair: nobility are strictly prohibited from the practice of ressurection as well. In some cases, a ritual is performed at the discretion of High Priestess Keppira D'bar to deem if one's soul is worthy of an extended lease on life. Pharasma speaks through her and judges the soul - but even if successful however, this gift is temporary - and only lasts until the soul has fulfilled its purpose in the Material Plane.");


// LAYER GROUPS //
var lg_gMil = L.featureGroup([g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13]).on('click', zoomToMax);
var lg_hInn = L.featureGroup([h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13,h14,h15,h16,h17,h18,h19]).on('click', zoomToMax);
var lg_rTav = L.featureGroup([r1,r2,r3,r4,r5,r6,r7,r8,r9,r10]).on('click', zoomToMax);
var lg_sShop = L.featureGroup([s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18]).on('click', zoomToMax);
var lg_lSite = L.featureGroup([v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13]).on('click', zoomToMax);
var lg_tSch = L.featureGroup([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11]).on('click', zoomToMax);

function zoomToMax(e) {
  map.setView(e.latlng, 4)
};

// Control overlays
var overlays = {
  "Goverment & Military" : lg_gMil,
  "Homes & Inns" : lg_hInn,
  "Restaurants & Taverns" : lg_rTav,
  "Shops & Services" : lg_sShop,
  "Temples & Schools" : lg_tSch,
  "Sites & Landmarks" : lg_lSite
};

L.control.layers(null, overlays).addTo(map);
